In [1]:
#import libary

In [1]:
import pandas as pd

In [2]:
#import a csv file

In [3]:
df = pd.read_csv('data for cleaning.csv')

In [4]:
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
62,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
63,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
64,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
65,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [5]:
#renmae the columns

In [6]:
df = df.rename(columns = {'NO' : 'Not_Outs', 'HS' : 'High_Inns_Scores',  'BF' : 'Balls_Faced', 'SR' : 'Strike_rates'})

In [7]:
df

,Player,Span,Mat,Inns,Not_Outs,Runs,High_Inns_Scores,Ave,Balls_Faced,Strike_rates,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
62,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
63,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
64,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
65,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [8]:
#Find a null value

In [9]:
df.isnull().sum()

Player              0
Span                0
Mat                 0
Inns                0
Not_Outs            0
Runs                0
High_Inns_Scores    0
Ave                 0
Balls_Faced         0
Strike_rates        0
100                 0
50                  0
0                   0
4s                  0
6s                  0
dtype: int64

In [10]:
df[df['Balls_Faced'].isna()  == 1]

Empty DataFrame
Columns: [Player, Span, Mat, Inns, Not_Outs, Runs, High_Inns_Scores, Ave, Balls_Faced, Strike_rates, 100, 50, 0, 4s, 6s]
Index: []

In [11]:
df

,Player,Span,Mat,Inns,Not_Outs,Runs,High_Inns_Scores,Ave,Balls_Faced,Strike_rates,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
62,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
63,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
64,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
65,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [12]:
df['Balls_Faced'] =  df['Balls_Faced'].fillna(0)

In [13]:
df

,Player,Span,Mat,Inns,Not_Outs,Runs,High_Inns_Scores,Ave,Balls_Faced,Strike_rates,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
62,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
63,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
64,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
65,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [14]:
#Drop and remove the duplicates

In [15]:
pd.set_option('display.max_rows', None)

In [16]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30     True
31    False
32    False
33    False
34    False
35     True
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59    False
60    False
61    False
62    False
63    False
64    False
65    False
dtype: bool

In [17]:
df.drop_duplicates(inplace = True)

In [18]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
31    False
32    False
33    False
34    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59    False
60    False
61    False
62    False
63    False
64    False
65    False
dtype: bool

In [19]:
df

,Player,Span,Mat,Inns,Not_Outs,Runs,High_Inns_Scores,Ave,Balls_Faced,Strike_rates,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6
5,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4
6,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,-,0.00,15,19,6,258+,2
9,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27
10,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
11,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51
12,SPD Smith (AUS),2010-2024,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54
13,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8
14,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,-,0.00,15,14,1,107+,11
15,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7
16,Saud Shakeel (PAK),2022-2024,12,23,3,1126,208*,56.30,2413,46.66,3,6,1,123,1
17,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
18,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2
19,KS Williamson (NZ),2010-2024,102,180,17,8881,251,54.48,17267,51.43,32,35,11,982,26
21,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1
22,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6
23,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16
24,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6
25,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69
26,HC Brook (ENG),2022-2024,18,30,1,1558,186,53.72,1795,86.79,5,9,1,181,26
27,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88
28,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48
29,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21
31,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51
32,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70
33,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73
34,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3
36,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20
37,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39
38,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36
39,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26
40,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20
41,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82
42,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64
43,JE Root (ENG),2012-2024,146,267,22,12402,254,50.62,21785,56.92,34,64,12,1343,44
44,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28
45,IVA Richards (WI),1974-1991,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952+,84
46,DCS Compton (ENG),1937-1957,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342+,3
47,DPMD Jayawardene (SL),1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61
48,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48
49,M Labuschagne (AUS),2018-2024,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12
50,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240+,11
51,CP Mead (ENG),1911-1928,17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38+,0
52,V Sehwag (ICC/IND),2001-2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91
53,Abid Ali (PAK),2019-2021,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5
54,MJ Clarke (AUS),2004-2015,115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39
55,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123+,20
56,B Mitchell (SA),1929-1949,42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41+,1
57,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,-,0.00,5,6,3,51+,0
58,TT Samaraweera (SL),2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7
59,V Kohli (IND),2011-2024,115*,193,11,8871,254*,48.74,15967,55.55,29,30,14,993,26
60,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427+,1
61,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23
62,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
63,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
64,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
65,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [20]:
#Split starting and ending years

In [21]:
df['Span'].str.split(pat = '-')

0     [1928, 1948]
1     [2015, 2016]
2     [1963, 1970]
3     [1930, 1954]
4     [1924, 1935]
5     [1931, 1939]
6     [1955, 1968]
8     [1948, 1958]
9     [1927, 1947]
10    [1954, 1974]
11    [2000, 2015]
12    [2010, 2024]
13    [1908, 1930]
14    [1948, 1960]
15    [1937, 1955]
16    [2022, 2024]
17    [1995, 2013]
18    [1921, 1929]
19    [2010, 2024]
21    [1968, 1973]
22    [1993, 1995]
23    [1970, 1984]
24    [1935, 1951]
25    [1989, 2013]
26    [2022, 2024]
27    [1990, 2006]
28    [1976, 1993]
29    [1996, 2012]
31    [1998, 2010]
32    [2000, 2017]
33    [1995, 2012]
34    [1920, 1929]
36    [1992, 2002]
37    [2005, 2013]
38    [1994, 2015]
39    [1971, 1987]
40    [1985, 2004]
41    [1994, 2009]
42    [2004, 2018]
43    [2012, 2024]
44    [1978, 1994]
45    [1974, 1991]
46    [1937, 1957]
47    [1997, 2014]
48    [1992, 2007]
49    [2018, 2024]
50    [1948, 1963]
51    [1911, 1928]
52    [2001, 2013]
53    [2019, 2021]
54    [2004, 2015]
55    [1961, 1966]
56    [1929, 1949]
57    [1893, 1905]
58    [2001, 2013]
59    [2011, 2024]
60    [1948, 1963]
61    [1965, 1981]
62    [2002, 2014]
63    [1924, 1934]
64    [1930, 1938]
65    [1928, 1934]
Name: Span, dtype: object

In [22]:
df.head(10)

,Player,Span,Mat,Inns,Not_Outs,Runs,High_Inns_Scores,Ave,Balls_Faced,Strike_rates,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6
5,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4
6,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,-,0.00,15,19,6,258+,2
9,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27
10,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+

In [23]:
df['Start_Year'] = df['Span'].str.split(pat = '-').str[0]

In [24]:
df['Final_Year'] = df['Span'].str.split(pat = '-').str[1]

In [25]:
df

,Player,Span,Mat,Inns,Not_Outs,Runs,High_Inns_Scores,Ave,Balls_Faced,Strike_rates,100,50,0,4s,6s,Start_Year,Final_Year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935
5,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,1931,1939
6,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27,1955,1968
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,-,0.00,15,19,6,258+,2,1948,1958
9,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27,1927,1947
10,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974
11,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015
12,SPD Smith (AUS),2010-2024,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024
13,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,1908,1930
14,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,-,0.00,15,14,1,107+,11,1948,1960
15,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7,1937,1955
16,Saud Shakeel (PAK),2022-2024,12,23,3,1126,208*,56.30,2413,46.66,3,6,1,123,1,2022,2024
17,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013
18,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2,1921,1929
19,KS Williamson (NZ),2010-2024,102,180,17,8881,251,54.48,17267,51.43,32,35,11,982,26,2010,2024
21,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1,1968,1973
22,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995
23,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984
24,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6,1935,1951
25,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013
26,HC Brook (ENG),2022-2024,18,30,1,1558,186,53.72,1795,86.79,5,9,1,181,26,2022,2024
27,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006
28,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48,1976,1993
29,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012
31,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010
32,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017
33,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012
34,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3,1920,1929
36,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002
37,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013
38,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015
39,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26,1971,1987
40,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004
41,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009
42,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018
43,JE Root (ENG),2012-2024,146,267,22,12402,254,50.62,21785,56.92,34,64,12,1343,44,2012,2024
44,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994
45,IVA Richards (WI),1974-1991,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952+,84,1974,1991
46,DCS Compton (ENG),1937-1957,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342+,3,1937,1957
47,DPMD Jayawardene (SL),1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014
48,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007
49,M Labuschagne (AUS),2018-2024,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024
50,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240+,11,1948,1963
51,CP Mead (ENG),1911-1928,17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38+,0,1911,1928
52,V Sehwag (ICC/IND),2001-2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013
53,Abid Ali (PAK),2019-2021,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5,2019,2021
54,MJ Clarke (AUS),2004-2015,115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39,2004,2015
55,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123+,20,1961,1966
56,B Mitchell (SA),1929-1949,42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41+,1,1929,1949
57,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,-,0.00,5,6,3,51+,0,1893,1905
58,TT Samaraweera (SL),2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013
59,V Kohli (IND),2011-2024,115*,193,11,8871,254*,48.74,15967,55.55,29,30,14,993,26,2011,2024
60,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427+,1,1948,1963
61,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981
62,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
63,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934
64,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938
65,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934

In [26]:
df = df.drop(['Span'], axis = 1)

In [27]:
#Split the nationality of the players

In [28]:
df['Player'].str.split(pat = '(')

0             [DG Bradman , AUS)]
1               [AC Voges , AUS)]
2              [RG Pollock , SA)]
3              [GA Headley , WI)]
4            [H Sutcliffe , ENG)]
5              [E Paynter , ENG)]
6          [KF Barrington , ENG)]
8               [ED Weekes , WI)]
9             [WR Hammond , ENG)]
10              [GS Sobers , WI)]
11          [KC Sangakkara , SL)]
12             [SPD Smith , AUS)]
13              [JB Hobbs , ENG)]
14             [CL Walcott , WI)]
15              [L Hutton , ENG)]
16          [Saud Shakeel , PAK)]
17          [JH Kallis , ICC/SA)]
18          [GE Tyldesley , ENG)]
19          [KS Williamson , NZ)]
21               [CA Davis , WI)]
22             [VG Kambli , IND)]
23           [GS Chappell , AUS)]
24              [AD Nourse , SA)]
25          [SR Tendulkar , IND)]
26              [HC Brook , ENG)]
27            [BC Lara , ICC/WI)]
28         [Javed Miandad , PAK)]
29          [R Dravid , ICC/IND)]
31       [Mohammad Yousuf , PAK)]
32           [Younis Khan , PAK)]
33            [RT Ponting , AUS)]
34               [J Ryder , AUS)]
36              [A Flower , ZIM)]
37            [MEK Hussey , AUS)]
38          [S Chanderpaul , WI)]
39           [SM Gavaskar , IND)]
40              [SR Waugh , AUS)]
41             [ML Hayden , AUS)]
42         [AB de Villiers , SA)]
43               [JE Root , ENG)]
44             [AR Border , AUS)]
45           [IVA Richards , WI)]
46           [DCS Compton , ENG)]
47       [DPMD Jayawardene , SL)]
48    [Inzamam-ul-Haq , ICC/PAK)]
49         [M Labuschagne , AUS)]
50            [FMM Worrell , WI)]
51               [CP Mead , ENG)]
52          [V Sehwag , ICC/IND)]
53              [Abid Ali , PAK)]
54             [MJ Clarke , AUS)]
55               [KC Bland , SA)]
56             [B Mitchell , SA)]
57        [Hon.FS Jackson , ENG)]
58         [TT Samaraweera , SL)]
59               [V Kohli , IND)]
60             [RN Harvey , AUS)]
61            [KD Walters , AUS)]
62           [GC Smith , ICC/SA)]
63           [WH Ponsford , AUS)]
64             [SJ McCabe , AUS)]
65            [DR Jardine , ENG)]
Name: Player, dtype: object

In [29]:
df['Nationality'] = df['Player'].str.split(pat = '(').str[1]

In [30]:
df.head(5)

,Player,Mat,Inns,Not_Outs,Runs,High_Inns_Scores,Ave,Balls_Faced,Strike_rates,100,50,0,4s,6s,Start_Year,Final_Year,Nationality
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS)
1,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS)
2,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA)
3,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI)
4,H Sutcliffe (ENG),54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,ENG)

In [31]:
df['Nationality'] = df['Nationality'].str.rstrip(')')

In [32]:
df.head()

,Player,Mat,Inns,Not_Outs,Runs,High_Inns_Scores,Ave,Balls_Faced,Strike_rates,100,50,0,4s,6s,Start_Year,Final_Year,Nationality
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS
1,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
2,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
3,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI
4,H Sutcliffe (ENG),54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,ENG

In [33]:
df['Player'] = df['Player'].str.split(pat = '(').str[0]

In [34]:
df

,Player,Mat,Inns,Not_Outs,Runs,High_Inns_Scores,Ave,Balls_Faced,Strike_rates,100,50,0,4s,6s,Start_Year,Final_Year,Nationality
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI
4,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,ENG
5,E Paynter,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,1931,1939,ENG
6,KF Barrington,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27,1955,1968,ENG
8,ED Weekes,48,81,5,4455,207,58.61,-,0.00,15,19,6,258+,2,1948,1958,WI
9,WR Hammond,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27,1927,1947,ENG
10,GS Sobers,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974,WI
11,KC Sangakkara,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL
12,SPD Smith,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,AUS
13,JB Hobbs,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,1908,1930,ENG
14,CL Walcott,44,74,7,3798,220,56.68,-,0.00,15,14,1,107+,11,1948,1960,WI
15,L Hutton,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7,1937,1955,ENG
16,Saud Shakeel,12,23,3,1126,208*,56.30,2413,46.66,3,6,1,123,1,2022,2024,PAK
17,JH Kallis,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA
18,GE Tyldesley,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2,1921,1929,ENG
19,KS Williamson,102,180,17,8881,251,54.48,17267,51.43,32,35,11,982,26,2010,2024,NZ
21,CA Davis,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1,1968,1973,WI
22,VG Kambli,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND
23,GS Chappell,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984,AUS
24,AD Nourse,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6,1935,1951,SA
25,SR Tendulkar,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013,IND
26,HC Brook,18,30,1,1558,186,53.72,1795,86.79,5,9,1,181,26,2022,2024,ENG
27,BC Lara,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI
28,Javed Miandad,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48,1976,1993,PAK
29,R Dravid,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND
31,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK
32,Younis Khan,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK
33,RT Ponting,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS
34,J Ryder,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3,1920,1929,AUS
36,A Flower,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM
37,MEK Hussey,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS
38,S Chanderpaul,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI
39,SM Gavaskar,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26,1971,1987,IND
40,SR Waugh,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS
41,ML Hayden,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS
42,AB de Villiers,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA
43,JE Root,146,267,22,12402,254,50.62,21785,56.92,34,64,12,1343,44,2012,2024,ENG
44,AR Border,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994,AUS
45,IVA Richards,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952+,84,1974,1991,WI
46,DCS Compton,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342+,3,1937,1957,ENG
47,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,SL
48,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,ICC/PAK
49,M Labuschagne,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,AUS
50,FMM Worrell,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240+,11,1948,1963,WI
51,CP Mead,17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38+,0,1911,1928,ENG
52,V Sehwag,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,ICC/IND
53,Abid Ali,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK
54,MJ Clarke,115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39,2004,2015,AUS
55,KC Bland,21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123+,20,1961,1966,SA
56,B Mitchell,42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41+,1,1929,1949,SA
57,Hon.FS Jackson,20,33,4,1415,144*,48.79,-,0.00,5,6,3,51+,0,1893,1905,ENG
58,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,SL
59,V Kohli,115*,193,11,8871,254*,48.74,15967,55.55,29,30,14,993,26,2011,2024,IND
60,RN Harvey,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427+,1,1948,1963,AUS
61,KD Walters,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525+,23,1965,1981,AUS
62,GC Smith,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
63,WH Ponsford,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,AUS
64,SJ McCabe,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,AUS
65,DR Jardine,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,ENG

In [35]:
#Change data types as High_Inns_Scores should be an int

In [36]:
df.dtypes

Player               object
Mat                  object
Inns                  int64
Not_Outs              int64
Runs                  int64
High_Inns_Scores     object
Ave                 float64
Balls_Faced          object
Strike_rates        float64
100                   int64
50                    int64
0                     int64
4s                   object
6s                   object
Start_Year           object
Final_Year           object
Nationality          object
dtype: object

In [37]:
df.head(10)

,Player,Mat,Inns,Not_Outs,Runs,High_Inns_Scores,Ave,Balls_Faced,Strike_rates,100,50,0,4s,6s,Start_Year,Final_Year,Nationality
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI
4,H Sutcliffe,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,ENG
5,E Paynter,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,1931,1939,ENG
6,KF Barrington,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27,1955,1968,ENG
8,ED Weekes,48,81,5,4455,207,58.61,-,0.00,15,19,6,258+,2,1948,1958,WI
9,WR Hammond,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27,1927,1947,ENG
10,GS Sobers,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974,WI

In [38]:
df['High_Inns_Scores'] = df['High_Inns_Scores'].str.rstrip('*')

In [39]:
df['High_Inns_Scores'] = df['High_Inns_Scores'].astype('int')

In [40]:
df['4s'] = df['4s'].str.rstrip('+')

In [41]:
df['Balls_Faced'] = df['Balls_Faced'].str.rstrip('+')

In [42]:
df['Balls_Faced'] = df['Balls_Faced'].replace('-', 0)

In [43]:
df.head(15)

,Player,Mat,Inns,Not_Outs,Runs,High_Inns_Scores,Ave,Balls_Faced,Strike_rates,100,50,0,4s,6s,Start_Year,Final_Year,Nationality
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954,WI
4,H Sutcliffe,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,1924,1935,ENG
5,E Paynter,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,1931,1939,ENG
6,KF Barrington,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,1955,1968,ENG
8,ED Weekes,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958,WI
9,WR Hammond,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,1927,1947,ENG
10,GS Sobers,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32+,1954,1974,WI
11,KC Sangakkara,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL
12,SPD Smith,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,AUS
13,JB Hobbs,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,1908,1930,ENG
14,CL Walcott,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960,WI
15,L Hutton,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,1937,1955,ENG

In [44]:
df['Balls_Faced'] = df['Balls_Faced'].astype('float')

In [45]:
df.head(10)

,Player,Mat,Inns,Not_Outs,Runs,High_Inns_Scores,Ave,Balls_Faced,Strike_rates,100,50,0,4s,6s,Start_Year,Final_Year,Nationality
0,DG Bradman,52,80,10,6996,334,99.94,9800.0,58.60,29,13,7,626,6,1928,1948,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667.0,55.68,5,4,2,186,5,2015,2016,AUS
2,RG Pollock,23,41,4,2256,274,60.97,1707.0,54.48,7,11,1,246,11,1963,1970,SA
3,GA Headley,22,40,4,2190,270,60.83,416.0,56.00,10,5,2,104,1,1930,1954,WI
4,H Sutcliffe,54,84,9,4555,194,60.73,6558.0,34.59,16,23,2,202,6,1924,1935,ENG
5,E Paynter,20,31,5,1540,243,59.23,1288.0,45.88,4,7,3,125,4,1931,1939,ENG
6,KF Barrington,82,131,15,6806,256,58.67,4957.0,42.42,20,35,5,591,27,1955,1968,ENG
8,ED Weekes,48,81,5,4455,207,58.61,0.0,0.00,15,19,6,258,2,1948,1958,WI
9,WR Hammond,85,140,16,7249,336,58.45,7491.0,38.07,22,24,4,419,27,1927,1947,ENG
10,GS Sobers,93,160,21,8032,365,57.78,4063.0,53.58,26,30,12,593,32+,1954,1974,WI

In [46]:
df = df.astype({'Start_Year' : 'int', 'Final_Year' : 'int'})

In [47]:
df.dtypes

Player               object
Mat                  object
Inns                  int64
Not_Outs              int64
Runs                  int64
High_Inns_Scores      int32
Ave                 float64
Balls_Faced         float64
Strike_rates        float64
100                   int64
50                    int64
0                     int64
4s                   object
6s                   object
Start_Year            int32
Final_Year            int32
Nationality          object
dtype: object

In [48]:
 ###Question what are the career length of each player

In [49]:
df['Career_Length'] = df['Final_Year'] - df['Start_Year']

In [60]:
df

,Player,Mat,Inns,Not_Outs,Runs,High_Inns_Scores,Ave,Balls_Faced,Strike_rates,100,50,0,4s,6s,Start_Year,Final_Year,Nationality,Career_Length
0,DG Bradman,52,80,10,6996,334,99.94,9800.0,58.60,29,13,7,626,6,1928,1948,AUS,20
1,AC Voges,20,31,7,1485,269,61.87,2667.0,55.68,5,4,2,186,5,2015,2016,AUS,1
2,RG Pollock,23,41,4,2256,274,60.97,1707.0,54.48,7,11,1,246,11,1963,1970,SA,7
3,GA Headley,22,40,4,2190,270,60.83,416.0,56.00,10,5,2,104,1,1930,1954,WI,24
4,H Sutcliffe,54,84,9,4555,194,60.73,6558.0,34.59,16,23,2,202,6,1924,1935,ENG,11
5,E Paynter,20,31,5,1540,243,59.23,1288.0,45.88,4,7,3,125,4,1931,1939,ENG,8
6,KF Barrington,82,131,15,6806,256,58.67,4957.0,42.42,20,35,5,591,27,1955,1968,ENG,13
8,ED Weekes,48,81,5,4455,207,58.61,0.0,0.00,15,19,6,258,2,1948,1958,WI,10
9,WR Hammond,85,140,16,7249,336,58.45,7491.0,38.07,22,24,4,419,27,1927,1947,ENG,20
10,GS Sobers,93,160,21,8032,365,57.78,4063.0,53.58,26,30,12,593,32+,1954,1974,WI,20
11,KC Sangakkara,134,233,17,12400,319,57.40,22882.0,54.19,38,52,11,1491,51,2000,2015,SL,15
12,SPD Smith,109,195,25,9685,239,56.97,18100.0,53.50,32,41,10,1063,54,2010,2024,AUS,14
13,JB Hobbs,61,102,7,5410,211,56.94,5363.0,46.22,15,28,4,276,8,1908,1930,ENG,22
14,CL Walcott,44,74,7,3798,220,56.68,0.0,0.00,15,14,1,107,11,1948,1960,WI,12
15,L Hutton,79,138,15,6971,364,56.67,2844.0,39.34,19,33,5,358,7,1937,1955,ENG,18
16,Saud Shakeel,12,23,3,1126,208,56.30,2413.0,46.66,3,6,1,123,1,2022,2024,PAK,2
17,JH Kallis,166,280,40,13289,224,55.37,28903.0,45.97,45,58,16,1488,97,1995,2013,ICC/SA,18
18,GE Tyldesley,14,20,2,990,122,55.00,178.0,29.21,3,6,2,37,2,1921,1929,ENG,8
19,KS Williamson,102,180,17,8881,251,54.48,17267.0,51.43,32,35,11,982,26,2010,2024,NZ,14
21,CA Davis,15,29,5,1301,183,54.20,665.0,35.48,4,4,1,65,1,1968,1973,WI,5
22,VG Kambli,17,21,1,1084,227,54.20,1823.0,59.46,4,3,3,124,6,1993,1995,IND,2
23,GS Chappell,87,151,19,7110,247,53.86,13079.0,51.53,24,31,12,755,16,1970,1984,AUS,14
24,AD Nourse,34,62,7,2960,231,53.81,108.0,63.88,9,14,3,115,6,1935,1951,SA,16
25,SR Tendulkar,200,329,33,15921,248,53.78,29437.0,54.04,51,68,14,2058,69,1989,2013,IND,24
26,HC Brook,18,30,1,1558,186,53.72,1795.0,86.79,5,9,1,181,26,2022,2024,ENG,2
27,BC Lara,131,232,6,11953,400,52.88,19753.0,60.51,34,48,17,1559,88,1990,2006,ICC/WI,16
28,Javed Miandad,124,189,21,8832,280,52.57,15164.0,45.99,23,43,6,788,48,1976,1993,PAK,17
29,R Dravid,164,286,32,13288,270,52.31,31258.0,42.51,36,63,8,1654,21,1996,2012,ICC/IND,16
31,Mohammad Yousuf,90,156,12,7530,223,52.29,14372.0,52.39,24,33,11,957,51,1998,2010,PAK,12
32,Younis Khan,118,213,19,10099,313,52.05,19375.0,52.12,34,33,19,1082,70,2000,2017,PAK,17
33,RT Ponting,168,287,29,13378,257,51.85,22782.0,58.72,41,62,17,1509,73,1995,2012,AUS,17
34,J Ryder,20,32,5,1394,201,51.62,2035.0,44.86,3,9,1,102,3,1920,1929,AUS,9
36,A Flower,63,112,19,4794,232,51.54,10636.0,45.07,12,27,5,543,20,1992,2002,ZIM,10
37,MEK Hussey,79,137,16,6235,195,51.52,12436.0,50.13,19,29,12,685,39,2005,2013,AUS,8
38,S Chanderpaul,164,280,49,11867,203,51.37,27395.0,43.31,30,66,15,1285,36,1994,2015,WI,21
39,SM Gavaskar,125,214,16,10122,236,51.12,14184.0,43.35,34,45,12,908,26,1971,1987,IND,16
40,SR Waugh,168,260,46,10927,200,51.06,22461.0,48.64,32,50,22,1175,20,1985,2004,AUS,19
41,ML Hayden,103,184,14,8625,380,50.73,14349.0,60.10,30,29,14,1049,82,1994,2009,AUS,15
42,AB de Villiers,114,191,18,8765,278,50.66,16077.0,54.51,22,46,8,1024,64,2004,2018,SA,14
43,JE Root,146,267,22,12402,254,50.62,21785.0,56.92,34,64,12,1343,44,2012,2024,ENG,12
44,AR Border,156,265,44,11174,205,50.56,27002.0,41.09,27,63,11,1161,28,1978,1994,AUS,16
45,IVA Richards,121,182,12,8540,291,50.23,9613.0,69.77,24,45,10,952,84,1974,1991,WI,17
46,DCS Compton,78,131,15,5807,278,50.06,2731.0,38.81,17,28,10,342,3,1937,1957,ENG,20
47,DPMD Jayawardene,149,252,15,11814,374,49.84,22959.0,51.45,34,50,15,1387,61,1997,2014,SL,17
48,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345.0,54.02,25,46,15,1105,48,1992,2007,ICC/PAK,15
49,M Labuschagne,50,90,7,4114,215,49.56,7809.0,52.68,11,20,4,463,12,2018,2024,AUS,6
50,FMM Worrell,51,87,9,3860,261,49.48,488.0,40.16,9,22,11,240,11,1948,1963,WI,15
51,CP Mead,17,26,2,1185,182,49.37,619.0,30.04,4,3,3,38,0,1911,1928,ENG,17
52,V Sehwag,104,180,6,8586,319,49.34,10441.0,82.23,23,32,16,1233,91,2001,2013,ICC/IND,12
53,Abid Ali,16,26,2,1180,215,49.16,2445.0,48.26,4,3,2,148,5,2019,2021,PAK,2
54,MJ Clarke,115,198,22,8643,329,49.10,15456.0,55.92,28,27,9,978,39,2004,2015,AUS,11
55,KC Bland,21,39,5,1669,144,49.08,885.0,37.74,3,9,2,123,20,1961,1966,SA,5
56,B Mitchell,42,80,9,3471,189,48.88,158.0,29.11,8,21,3,41,1,1929,1949,SA,20
57,Hon.FS Jackson,20,33,4,1415,144,48.79,0.0,0.00,5,6,3,51,0,1893,1905,ENG,12
58,TT Samaraweera,81,132,20,5462,231,48.76,11641.0,46.92,14,30,11,633,7,2001,2013,SL,12
59,V Kohli,115*,193,11,8871,254,48.74,15967.0,55.55,29,30,14,993,26,2011,2024,IND,13
60,RN Harvey,79,137,10,6149,205,48.41,1799.0,43.74,21,24,7,427,1,1948,1963,AUS,15
61,KD Walters,74,125,14,5357,250,48.26,8662.0,49.16,15,33,4,525,23,1965,1981,AUS,16
62,GC Smith,117,205,13,9265,277,48.25,15525.0,59.67,27,38,11,1165,24,2002,2014,ICC/SA,12
63,WH Ponsford,29,48,4,2122,266,48.22,3118.0,44.77,7,6,1,119,0,1924,1934,AUS,10
64,SJ McCabe,39,62,5,2748,232,48.21,3217.0,60.02,6,13,4,241,5+,1930,1938,AUS,8
65,DR Jardine,22,33,6,1296,127,48.00,2110.0,25.59,1,10,2,53,0,1928,1934,ENG,6

In [51]:
##Question 1: what is the average career length of all players

In [52]:
df['Career_Length'].mean().round(2)

13.16

In [53]:
##Question 2: What is the average Strike_rates of players who played over 10 years

In [54]:
Over_Decade = df[df['Career_Length'] > 10]

In [55]:
Over_Decade['Strike_rates'].mean()

47.956136363636354

In [56]:
##Question 3: What is the number of players who played before 1960

In [57]:
df[df['Start_Year'] < 1960]['Player'].count()

23

In [58]:
##Question 4: What country has the highest "High_Inns_Scores"?

In [96]:
Highest_Inns_Scores = df.groupby('Nationality')['High_Inns_Scores'].max().sort_values(ascending=False)

In [97]:
Highest_Inns_Scores.head(1)

Nationality
ICC/WI    400
Name: High_Inns_Scores, dtype: int32